services:
  app:
    image: colab_tester
    hostname: test-server-${HOSTNAME}
    environment:
      - PARENT=${HOSTNAME}
    volumes:
      - src:/home/colab/src/app
      - asdf-installs:/home/colab/.asdf/installs
      - asdf-shims:/home/colab/.asdf/shims
    depends_on:
      - db
      - selenium
  db:
    image: colab_db
    tmpfs:
      - /var/lib/mysql
    ports:
      - 31337:3306
  selenium:
    image: colab_browser
    # The following inspired by:
    # https://medium.com/the-curve-tech-blog/dealing-with-cryptic-selenium-webdriver-error-invalidsessioniderror-errors-9c15abc68fdf
    shm_size: '256mb'
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900

volumes:
  src:
  asdf-installs:
  asdf-shims:
  mariadb-data:
