require: 
  - rubocop-thread_safety
  - rubocop-capybara

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rb'
    - '**/*.erb'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Metrics:
    Enabled: false
Metrics/ClassLength:
    Enabled: false
Metrics/BlockLength:
    Enabled: false
Metrics/MethodLength:
    Enabled: false
Style/YodaCondition:
  EnforcedStyle: require_for_equality_operators_only
Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: space
Layout/SpaceInsideParens:
  EnforcedStyle: space
