require: 
  - rubocop-thread_safety
  - rubocop-performance

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rb'
    - '**/*.erb'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
