version: "3.7"
services:
  app:
    image: colab_app
    ports:
      - '31337:31337'
    volumes:
      - type: bind
        source: ~/.ssh
        target: /home/colab/.ssh
      - src:/home/colab/src/app
      - asdf-installs:/home/colab/.asdf/installs
  db:
    image: colab_db
  browser:
    image: colab_browser
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900

volumes:
  src:
  asdf-installs:

