services:
  app:
    image: colab_dev_server
    hostname: dev-serv-${HOSTNAME}
    environment:
      - PARENT=${HOSTNAME}
    ports:
      - 3000:3000
      - 3035:3035
    depends_on:
      - db
    volumes:
      - ../../:/home/colab/src/app:cached
      - "${HOME}/.ssh:/root/.ssh-localhost:ro"
    command: bash -c "sleep infinity"
  db:
    image: colab_db
    restart: unless-stopped
    ports:
      - 31337:3306
    volumes:
      - devdata:/var/lib/mysql

  # Docs at https://github.com/MRColorR/vnc-browser
  browser:
    container_name: vnc-browser
    image: mrcolorrain/vnc-browser:debian
    ports:
      - 5909:5900
      - 6080:6080
    environment:
      VNC_PASSWORD: "password"
      AUTO_START_XTERM: "false"
    restart: unless-stopped

  selenium:
    image: colab_browser
    shm_size: '256mb'
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900

  moodle:
    image: colab_moodle
    depends_on:
      - db
    environment:
      - MOODLE_LANG=en
      - LANGUAGE=en_US:en
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle

      - MOODLE_REVERSEPROXY=false
      - MOODLE_SSLPROXY=false
      - MOODLE_EMAIL=user@example.com
      - MOODLE_SITE_NAME=CoLab-Testing
      - MOODLE_USERNAME=moodleuser
      - MOODLE_PASSWORD=CHANGEME

      - MOODLE_SMTP_HOST=smtp.gmail.com
      - MOODLE_SMTP_PORT_NUMBER=587
      - MOODLE_SMTP_USER=micah.modell+moodle@gmail.com
      - MOODLE_SMTP_PASSWORD=CHANGEME
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[colab-moodle]
    ports:
      - 8080:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html


volumes:
  mariadb-data:
  ffconfig:
  devdata:
  moodledata:
  moodlehtml:

