version: "3.7"
services:
  app:
    image: colab_dev_server
    hostname: dev-serv-${HOSTNAME}
    environment:
      - PARENT=${HOSTNAME}
    ports:
      - 3000:3000
      - 3035:3035
    depends_on:
      - db
      - redis
      - moodle
    volumes:
      - ../../:/home/colab/src/app
      - asdf-installs:/home/colab/.asdf/installs
      - asdf-shims:/home/colab/.asdf/shims
  db:
    image: colab_db
    restart: unless-stopped
    ports:
      - 31337:3306
    volumes:
      - devdata:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: unless-stopped

  moodle:
    image: colab_moodle
    depends_on:
      - db
      - redis
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - SITE_URL=http://localhost
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=moodle
      - DB_PREFIX=mdl_
      - REDIS_HOST=redis
      - REVERSEPROXY=false
      - SSLPROXY=false
      - MOODLE_EMAIL=user@example.com
      - MOODLE_LANGUAGE=en
      - MOODLE_SITENAME=CoLab-Testing
      - MOODLE_USERNAME=moodleuser
      - MOODLE_PASSWORD=CHANGEME
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=micah.modell+moodle@gmail.com
      - SMTP_PROTOCOL=tls
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[colab-moodle]
    ports:
      - 80:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html


volumes:
  src:
  asdf-installs:
  asdf-shims:
  mariadb-data:
  devdata:
  moodledata:
  moodlehtml:

