# frozen_string_literal: true

class Concept < ApplicationRecord
  has_many :candidates, inverse_of: :concept, dependent: :nullify
  has_many :candidate_lists, through: :candidates
  has_many :bingo_games, through: :candidate_lists
  has_many :courses, through: :bingo_games

  normalizes :name, with: ->( name ) { Concept.standardize_concept name: name }

  # Generated by Clause 3/27/26 (free version)
  # far more brief than Gemini's generated version
  # The first attempt had an error, but when it was
  # pointed out, we were able to get it right after
  # a number of back-and-forths.
  # Ultimately, I learned a bit about regex and gsub.
  def self.standardize_concept(name:)
    name
      .strip
      # Collapse multiple spaces into a single space
      .gsub( /\s+/, ' ' )
      # Capitalise the first letter of each word
      .gsub(/[^-()\s]+/) {|word| word.capitalize}
      # Capitalize what's between parentheses
      .gsub(/\(([^)]+)\)/) { "(#{$~[1].upcase})" }
      # Capitalize what follows hyphens
      .gsub(/\((?<content>[^)]+)\)/) { "(#{$~[:content].upcase})" }
  end

end
